# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/lifrankfan/CrucialX6/PlantsVsZombie/ip_repo/hmdi_text_controller_1_0/src/pvzbackground_rom/pvzbackground_rom.xci
# IP: The module: 'pvzbackground_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/lifrankfan/CrucialX6/PlantsVsZombie/ip_repo/hmdi_text_controller_1_0/src/pvzbackground_rom/pvzbackground_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pvzbackground_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/lifrankfan/CrucialX6/PlantsVsZombie/ip_repo/hmdi_text_controller_1_0/src/pvzbackground_rom/pvzbackground_rom.xci
# IP: The module: 'pvzbackground_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/lifrankfan/CrucialX6/PlantsVsZombie/ip_repo/hmdi_text_controller_1_0/src/pvzbackground_rom/pvzbackground_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pvzbackground_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
