# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/lifrankfan/CrucialX6/PlantsVsZombie/PlantsVsZombie.srcs/sources_1/ip/digits_rom/digits_rom.xci
# IP: The module: 'digits_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/lifrankfan/CrucialX6/PlantsVsZombie/PlantsVsZombie.gen/sources_1/ip/digits_rom/digits_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'digits_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/lifrankfan/CrucialX6/PlantsVsZombie/PlantsVsZombie.srcs/sources_1/ip/digits_rom/digits_rom.xci
# IP: The module: 'digits_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/lifrankfan/CrucialX6/PlantsVsZombie/PlantsVsZombie.gen/sources_1/ip/digits_rom/digits_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'digits_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
